const ACTypes = {
  ADD_PRODUCT: "ADD_PRODUCT",
  ALL_PRODUCTS_REDUX: "ALL_PRODUCTS_REDUX",
  DEL_PRODUCTS_REDUX: "DEL_PRODUCTS_REDUX",
  ADD_PROD_SAGA: "ADD_PROD_SAGA",
  PRODUCT_SAGA: "PRODUCT_SAGA",
  DEL_PRODUCT_SAGA: "DEL_PRODUCT_SAGA"
};

export default ACTypes;
