export const actiontTypes = {
  ADD_GLOBAL_NEWS: "ADD_GLOBAL_NEWS",
  ADD_GLOBAL_NEWS_SAGA:"ADD_GLOBAL_NEWS_SAGA",
  GET_GLOBAL_NEWS_SAGA:"GET_GLOBAL_NEWS_SAGA",
  GET_GLOBAL_NEWS_REDUX:"GET_GLOBAL_NEWS_REDUX",
  ADD_LIKE_GLOBAL_SAGA:"ADD_LIKE_GLOBAL_SAGA",
  ADD_LIKE_GLOBAL_REDUX:"ADD_LIKE_GLOBAL_REDUX",
  DEL_NEWS_GLOBAL_SAGA:'DEL_NEWS_GLOBAL_SAGA',
  DEL_NEWS_GLOBAL_REDUX:'DEL_NEWS_GLOBAL_REDUX'
}
