export const localTypes = {
  ADD_LOCAL_NEWS: "ADD_LOCAL_NEWS",
  ADD_LOCAL_NEWS_SAGA:"ADD_LOCAL_NEWS_SAGA",
  GET_LOCAL_NEWS_SAGA:"GET_LOCAL_NEWS_SAGA",
  GET_LOCAL_NEWS_REDUX:"GET_LOCAL_NEWS_REDUX",
  ADD_LIKE_LOCAL_SAGA:"ADD_LIKE_LOCAL_SAGA",
  ADD_LIKE_LOCAL_REDUX:"ADD_LIKE_LOCAL_REDUX",
  DEL_NEWS_LOCAL_SAGA:'DEL_NEWS_LOCAL_SAGA',
  DEL_NEWS_LOCAL_REDUX:'DEL_NEWS_LOCAL_REDUX'
}
