export const GET_ALL_SERVICES = 'GET_ALL_SERVICES'
export const SAGA_API_SERVICES = 'SAGA_API_SERVICES'
export const ADD_SERVICE = 'ADD_SERVICE'
export const REQUEST_ADD_SERVICE_SAGA = 'REQUEST_ADD_SERVICE_SAGA'
export const DELETE_SERVICE = 'DELETE_SERVICE'
export const REQUEST_DEL_SERVICE_SAGA = 'REQUEST_DEL_SERVICE_SAGA'

