export const types = {
  AUTH_USER: "AUTH_USER",
  LOCATION: "LOCTION",
  SIGN_UP_AUTH: "SIGN_UP_AUTH",
  SIGN_UP_USER: "SIGN_UP_USER",
  SIGN_OUT_USER: 'SIGN_OUT_USER',
  OPEN_MODALE: 'OPEN_MODALE',
  INFO_USER_PAGE: 'INFO_USER_PAGE',
  INFO_USER_PAGE_EDIT: 'INFO_USER_PAGE_EDIT',

  SIGN_UP_USER_SAGA: "SIGN_UP_USER_SAGA",
  SIGN_OUT_USER_SAGA: 'SIGN_OUT_USER_SAGA',
  SIGN_IN_USER_SAGA: 'SIGN_IN_USER_SAGA',
  CHECK_IS_AUTH_SAGA: 'CHECK_IS_AUTH_SAGA',
  INFO_USER_PAGE_SAGA: 'INFO_USER_PAGE_SAGA',
  INFO_USER_PAGE_EDIT_SAGA: 'INFO_USER_PAGE_EDIT_SAGA'

}
